import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

load_dotenv()

connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"),
    host=os.getenv("MYSQL_HOST"),
    port=int(os.getenv("MYSQL_PORT", 3306)),
    database=os.getenv("MYSQL_DATABASE")
)

engine = create_engine(connection_url)


#1. Count the total number of customers.

query="SELECT*FROM customers"

df=pd.read_sql(query,engine)

count=df["customer_id"].count()
print("total number of customers:",count)

#2. Count the total number of loans.

query_1="SELECT*FROM loans"

df=pd.read_sql(query_1,engine)

loan_count=df["loan_id"].count()
print("total number of loans:",loan_count)

#3. Count the total number of payments.

query_2="SELECT*FROM payments"

df=pd.read_sql(query_2,engine)

payment_count=df["payment_id"].count()
print("total number of payments:",payment_count)

#4. Count the total number of branches.

query_3="SELECT*FROM branches"

df=pd.read_sql(query_3,engine)

branches_count=df["branch_id"].count()
print("total number of branches.",branches_count)

#5. Find the number of customers in each city.

query_4="SELECT customer_name,city FROM customers"

df=pd.read_sql(query_4,engine)

customer_city=df.groupby("city")["customer_name"].count()
print("customers in each city",customer_city)

#6. Find the number of branches in each city.

query_5="SELECT branch_name,city FROM branches"

df=pd.read_sql(query_5,engine)

branch_city=df.groupby("city")["branch_name"].count()
print("branches in each city",branch_city)

#9. Find the number of approved, rejected, and defaulted loans.

query_6="SELECT loan_status FROM loans"

df=pd.read_sql(query_6,engine)

loans=df["loan_status"].value_counts()
print("number of approved, rejected, and defaulted loans",loans)

#10. Check whether any table contains duplicate primary-key values.

tables={
    "customers":"customer_id",
    "loans":"loan_id",
    "payments":"payment_id",
    "branches":"branch_id",
    "loan_branches":"loan_id"
}
for table,id_colums in tables.items():

    query_7=f" SELECT {id_colums} FROM {table}"

    df=pd.read_sql(query_7,engine)

    if df[id_colums].duplicated().any():
        print(f"{table}:duplicate primary-key values found")
    else:
        print(f"{table}: no duplicates primary-key values")    

#13. Find the total number of loan taken by each customer.

query_8="SELECT customers.customer_name,loans.loan_id FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_8,engine)

take_loan=df.groupby("customer_name")["loan_id"].count()
print("total number of loan taken by each customer:",take_loan)

#14. Find the total loan amount taken by each customer.

query_9="SELECT customers.customer_name,loans.loan_amount FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_9,engine)
total_loan=df.groupby("customer_name")["loan_amount"].sum()
print("total loan amount taken by each customer",total_loan)

#15.Identify the customer with the highest total loan amount.

total_loans=df.groupby("customer_name")["loan_amount"].sum().idxmax()
print("total loan amount taken by each customer",total_loans)

#16. Find the average loan amount.

query_10="SELECT loan_amount FROM loans"

df=pd.read_sql(query_10,engine)

average_amount=df["loan_amount"].mean()
print("average loan amount:",average_amount)

#17. Find the average loan amount for each loan type.

query_11="SELECT loan_type,loan_amount FROM loans"

df=pd.read_sql(query_11,engine)

ave_loan_type=df.groupby("loan_type")["loan_amount"].mean()
print("average loan amount for each loan type",ave_loan_type)

#18. Find the total loan amount generated by each loan type.

total_loan_type=df.groupby("loan_type")["loan_amount"].sum()
print("total loan amount generated by each loan type",total_loan_type)

#19. Identify the loan type with the highest total loan value.

max_loan_type=df.groupby("loan_type")["loan_amount"].sum().idxmax()
print("loan type with the highest total loan value:",max_loan_type)

#20. Identify the highest-value loan.

highest_loan=df.loc[df["loan_amount"].idxmax()]
print("highest-value loan:",highest_loan)

#23. Find customers who have multiple loans.

query_12="SELECT customers.customer_name,loans.loan_id FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_12,engine)

total_loan=df.groupby("customer_name")["loan_id"].count()
mul_loan=total_loan[total_loan>1]
print("customers who have multiple loans:",mul_loan)

#24. Find customers with both high loan amounts and low credit scores.

query_13="SELECT customers.customer_name,loans.loan_amount AS high_loan , customers.credit_score AS low_score FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_13,engine)

highest_loan_credit=df.loc[(df["high_loan"].mean()<df["high_loan"]) &(df["low_score"].mean()>df["low_score"])]
print("customers with both high loan amounts and low credit scores:",highest_loan_credit)

#25. Find the average credit score by loan type.

query_14="SELECT customers.credit_score,loans.loan_type FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_14,engine)

ave_credit=df.groupby("loan_type")["credit_score"].mean()
print("average credit score by loan type",ave_credit)

#26. Find the average annual income by loan type.

query_15="SELECT customers.annual_income,loans.loan_type FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_15,engine)

ave_income=df.groupby("loan_type")["annual_income"].mean()
print("average annual income by loan type",ave_income)

#27. Compare average loan amounts across different credit-score ranges.

query_16='''SELECT customers.credit_score,loans.loan_amount ,CASE
WHEN customers.credit_score BETWEEN 590 AND 620 then '590-620'
WHEN customers.credit_score BETWEEN 735  AND 760 then '735-760'
WHEN customers.credit_score BETWEEN 780 AND 790 then '780-790'END AS credit_score_range
FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;'''

df=pd.read_sql(query_16,engine)

average_loans=df.groupby("credit_score_range")["loan_amount"].mean().reset_index()
print("Compare average loan amounts across different credit-score ranges",average_loans)

# 28 Calculate the default rate for different credit-score ranges.

query_17='''SELECT customers.credit_score,loans.loan_status , CASE
WHEN customers.credit_score BETWEEN 590 AND 620 then '590-620'
WHEN customers.credit_score BETWEEN 735  AND 760 then '735-760'
WHEN customers.credit_score BETWEEN 780 AND 790 then '780-790'END AS credit_score_range
FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;'''

df=pd.read_sql(query_17,engine)

loan_status=df.groupby("credit_score_range")["loan_status"].count()
default_loans=df[df["loan_status"]=="Defaulted"].groupby("credit_score_range")["loan_status"].count()
default_rate=(default_loans/loan_status)*100
print("default rate  for different credit-score renge",default_rate)

# 29 Identify the customer with the highest outstanding risk based on loan amount and credit profile

query_18="SELECT customers.customer_name,customers.credit_score,loans.loan_amount FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_18,engine)
average_loan_amount=df["loan_amount"].mean()
average_credit_score=df["credit_score"].mean()
print(average_loan_amount)
print(average_credit_score)

outstanding_risk=df.loc[(average_loan_amount<df["loan_amount"])&(average_credit_score>df["credit_score"])]
print("customer with the highest outstanding risk based on loan amount and credit profile",outstanding_risk)

#30. Find customers whose loan amount is above the overall average loan amount.

query_19="SELECT customers.customer_name,loans.loan_amount FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_19,engine)

average_loan_amount=df["loan_amount"].mean()
overall_average=df.loc[average_loan_amount<df["loan_amount"]]
print("customers whose loan amount is above the overall average loan amount",overall_average)

#36. Find the total payment amount for each loan.

query_20="SELECT payments.loan_id,payments.amount_paid FROM payments;"

df=pd.read_sql(query_20,engine)

total_payments=df.groupby("loan_id")["amount_paid"].sum()
print("total payment amount for each loan",total_payments)

#37. Identify the loan with the highest total payment amount.

highest_payment=total_payments.idxmax()
print("loan with the highest total payment amount",highest_payment)

#38. Calculate the payment success rate.

query_21="SELECT payment_status FROM payments;"

df=pd.read_sql(query_21,engine)
total_paid_status=len(df["payment_status"])
paid_total = df[df["payment_status"] == "Paid"]["payment_status"].count()
succees_rate=(paid_total/total_paid_status)*100
print("payment success rate:",succees_rate)

#40. Compare payment performance across loan types.

query_22="SELECT loans.loan_type,payments.payment_status FROM loans INNER JOIN payments ON loans.loan_id=payments.loan_id;"

df=pd.read_sql(query_22,engine)

payment_performance=df.groupby("loan_type")["payment_status"].value_counts()
print("Compare payment performance across loan types",payment_performance)

#41. Find the total number of loans handled by each branch.

query_23="SELECT branches.branch_name,loan_branches.loan_id FROM loan_branches INNER JOIN branches ON loan_branches.branch_id=branches.branch_id;" 

df=pd.read_sql(query_23,engine)

total_branches=df.groupby("branch_name")["loan_id"].count()
print("total number of loans handled by each branch",total_branches)

#42. Find the total loan amount handled by each branch.

query_24="SELECT branches.branch_name,loans.loan_amount FROM loan_branches INNER JOIN branches ON loan_branches.branch_id=branches.branch_id INNER JOIN loans ON loans.loan_id=loan_branches.loan_id;" 


df=pd.read_sql(query_24,engine)

total_loan_branches=df.groupby("branch_name")["loan_amount"].sum()
print("total loan amount handled by each branches",total_loan_branches)

#43. Identify the branch with the highest total loan amount.

highest_loan_branches=total_loan_branches.idxmax()
print("branch with the highest total loan amount:",highest_loan_branches)

#44. Find the number of defaulted loans for each branch.

query_24="SELECT branches.branch_name,loans.loan_status FROM loan_branches INNER JOIN branches ON loan_branches.branch_id=branches.branch_id INNER JOIN loans ON loans.loan_id=loan_branches.loan_id;" 

df=pd.read_sql(query_24,engine)
default_branches=df[df["loan_status"]=="Defaulted"].groupby("branch_name")["loan_status"].count()
print("number of defaulted loans for each branch",default_branches)

#45. Calculate the default rate for each branch.

total_loan_status=df.groupby("branch_name")["loan_status"].count()
default_total=df[df["loan_status"]=="Defaulted"].groupby("branch_name")["loan_status"].count()
default_rate_branches=(default_total/total_loan_status)*100
print("default rate for each branch",default_rate_branches)

#46. Compare average loan amounts across branches.

query_25="SELECT branches.branch_name,loans.loan_amount FROM loan_branches INNER JOIN branches ON loan_branches.branch_id=branches.branch_id INNER JOIN loans ON loans.loan_id=loan_branches.loan_id;" 

df=pd.read_sql(query_25,engine)

average_amount_branch=df.groupby("branch_name")["loan_amount"].mean()
print("compare average loan amounts across branches",average_amount_branch)

#47. Identify branches with higher payment issues.

query_26="SELECT branches.branch_name,payments.payment_status FROM loans INNER JOIN payments ON loans.loan_id=payments.loan_id INNER JOIN loan_branches ON loans.loan_id=loan_branches.loan_id INNER JOIN branches ON branches.branch_id=loan_branches.branch_id;"

df=pd.read_sql(query_26,engine)

issued=df[(df["payment_status"]=="Late")|(df["payment_status"]=="Missed")].groupby("branch_name")["payment_status"].count().idxmax()
print("branches with higher payment issues.",issued)

#51. Find the highest-value loan in each loan type.

query_27="SELECT loan_type,loan_amount FROM loans;"

df=pd.read_sql(query_27,engine)

highest_loan_type=df.groupby("loan_type")["loan_amount"].sum().idxmax()
print("highest-value loan in each loan type:",highest_loan_type)

#59. Calculate the percentage contribution of each loan type to total loan value.

query_28="SELECT loan_amount,loan_type FROM loans;"

df=pd.read_sql(query_28,engine)

total_loan=df.groupby("loan_type")["loan_amount"].sum()
total_value=df["loan_amount"].sum()
per=(total_loan/total_value)*100
print("percentage contribution of each loan type to total loan value.",per)

#60. Identify loan types with above-average default rates.

query_29="SELECT loan_status,loan_type FROM loans;"

df=pd.read_sql(query_29,engine)

def_count=df[df["loan_status"]=="Defaulted"].groupby("loan_type")["loan_status"].count()
tot_count=df.groupby("loan_type")["loan_status"].count()
def_rate=(def_count/tot_count)*100
ave_def_rate=def_rate.mean()
above_average=def_rate[def_rate>ave_def_rate]
print("loan type with above average reates",above_average)

#61. Bring relevant SQL results into Pandas and inspect the DataFrame.

query_30="SELECT*FROM customers;"
df=pd.read_sql(query_30,engine)
print(df)

#62. Check missing values.

print("Check missing values",df.isnull())

#63. Check duplicate records.

print("Check duplicate records",df.duplicated())

#64. Convert date columns to datetime.

query_31="SELECT*FROM loans;"

df=pd.read_sql(query_31,engine)
date=pd.to_datetime(df["loan_date"])
print("Convert date columns to datetime",date)

#66. Analyze loan amount distribution.

dis=df["loan_amount"].describe()
print("Analyze loan amount distribution",dis)

#67. Analyze customer income distribution.

query_32="SELECT*FROM customers"

df=pd.read_sql(query_32,engine)

dis_income=df["annual_income"].describe()
print("Analyze customer income distribution",dis_income)

#68. Analyze credit-score distribution.

dis_credit_score=df["credit_score"].describe()
print("Analyze credit-score distribution",dis_credit_score)

#69. Identify high-value customers.

query_33="SELECT loans.loan_amount,customers.customer_name FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_33,engine)

high_value=df.groupby("customer_name")["loan_amount"].sum().idxmax()
print("Identify high-value customers",high_value)

#70. Identify unusually high loan amounts.

query_34="SELECT loan_amount FROM loans;"

df=pd.read_sql(query_34,engine)

q1=df["loan_amount"].quantile(0.25)
q3=df["loan_amount"].quantile(0.75)
IQR=q3 -q1
upper_limit=q3+1.5*IQR
high_loan=df[df["loan_amount"]>upper_limit]
print("unusually high loan amounts",high_loan)

#71 Compare average loan amounts across cities.

query_35="SELECT customers.city,loans.loan_amount FROM customers INNER JOIN loans ON customers.customer_id=loans.customer_id;"

df=pd.read_sql(query_35,engine)

city_loan=df.groupby("city")["loan_amount"].mean()
print("Compare average loan amounts across cities:",city_loan)

#72. Compare customer income and credit scores using statistical analysis.

query_36="SELECT * FROM customers;"

df=pd.read_sql(query_36,engine)

statistical = df[["annual_income", "credit_score"]].describe()

correlation = df["annual_income"].corr(df["credit_score"])

print(statistical)
print("Compare customer income and credit scores:", correlation)