
-- @conn MySQL Local
-- 1. Count the total number of customers.

SELECT count(*)FROM food_delivery_db.customers;

--  2. Count the total number of restaurants.

SELECT count(*) FROM food_delivery_db.restaurants;

-- 3. Count the total number of orders.

SELECT count(*) FROM food_delivery_db.orders;

-- 4. Find the number of unique cities represented in the customer data.

SELECT count(DISTINCT city)  as unique_city FROM food_delivery_db.customers;

-- 7. Find the earliest order date.

SELECT min(order_date) FROM food_delivery_db.orders;

-- 8. Find the latest order date.

SELECT max(order_date) FROM food_delivery_db.orders;

-- 9. Find the number of delivered and cancelled orders.
 SELECT  order_status ,count(*)  AS total_order FROM food_delivery_db.orders WHERE order_status IN ("Delivered","Cancelled") GROUP BY order_status;
 
 
-- 11. Display customer name, order ID, order date, and order status.

SELECT customers.customer_name,orders.order_id,orders.order_date,orders.order_status FROM food_delivery_db.customers INNER JOIN orders on customers.customer_id=orders.customer_id;

-- 12. Display order ID, customer name, restaurant name, and restaurant city.

SELECT orders.order_id,customers.customer_name,restaurants.restaurant_name,restaurants.city FROM food_delivery_db.customers INNER JOIN orders on customers.customer_id=orders.customer_id INNER JOIN restaurants on restaurants.restaurant_id=orders.restaurant_id;

-- 16. Find the total revenue generated by each restaurant.

SELECT  restaurants.restaurant_name,sum(order_items.item_price*order_items.quantity) AS total_revenue  FROM food_delivery_db.restaurants INNER JOIN  orders ON restaurants.restaurant_id=orders.restaurant_id  INNER JOIN  order_items ON order_items.order_id=orders.order_id  WHERE orders.order_status="Delivered"GROUP BY restaurants.restaurant_name;

 -- 17. Identify the highest-revenue restaurant.
SELECT  restaurant_name,total_revenue FROM (SELECT restaurants.restaurant_name,sum(order_items.item_price*order_items.quantity) AS total_revenue  FROM food_delivery_db.restaurants INNER JOIN  orders ON restaurants.restaurant_id=orders.restaurant_id  INNER JOIN  order_items ON order_items.order_id=orders.order_id  WHERE orders.order_status="Delivered"GROUP BY restaurants.restaurant_name) AS renvenue_table ORDER BY total_revenue  DESC LIMIT 1;

-- 18. Find the total quantity of food items sold for each item.

SELECT item_name,sum(quantity)  as total_item FROM order_items GROUP BY item_name;

-- 19. Identify the most frequently purchased item.
SELECT item_name,total_item FROM (SELECT item_name,count(*) as total_item FROM order_items GROUP BY item_name) as most_freq  ORDER BY total_item DESC LIMIT 1;

-- 20. Find the average order value.

SELECT AVG(order_total) AS average_order_value FROM (SELECT order_id, SUM(quantity * item_price) AS order_total FROM food_delivery_db.order_items GROUP BY order_id) AS order_values;


-- 23. Find the cancellation rate for each restaurant.
SELECT restaurants.restaurant_name, COUNT(CASE WHEN orders.order_status = 'Cancelled' THEN 1 END) AS cancelled_orders, COUNT(*) AS total_orders,COUNT(CASE WHEN orders.order_status = 'Cancelled' THEN 1 END) * 100.0 / COUNT(*) AS cancellation_rate FROM  food_delivery_db.restaurants INNER JOIN food_delivery_db.orders ON restaurants.restaurant_id = orders.restaurant_id GROUP BY restaurants.restaurant_name;

-- 24. Identify restaurants with the highest cancellation rate.

SELECT restaurants.restaurant_name, COUNT(CASE WHEN orders.order_status = 'Cancelled' THEN 1 END) AS cancelled_orders, COUNT(*) AS total_orders,COUNT(CASE WHEN orders.order_status = 'Cancelled' THEN 1 END) * 100.0 / COUNT(*) AS cancellation_rate FROM restaurants INNER JOIN orders ON restaurants.restaurant_id = orders.restaurant_id GROUP BY restaurants.restaurant_name ORDER BY cancellation_rate DESC LIMIT 1;

-- 25. Find each customer's first order date.

SELECT customers.customer_name,orders.order_date as first_order FROM customers INNER JOIN orders ON customers.customer_id=orders.customer_id ORDER BY first_order ASC LIMIT 1;

-- 26. Find each customer's most recent order date.

SELECT customers.customer_name, MAX(orders.order_date) as recent_order FROM customers INNER JOIN orders ON customers.customer_id=orders.customer_id GROUP BY customers.customer_name ;

-- 27. Rank restaurants by revenue within each city.

 SELECT restaurants.city,restaurants.restaurant_name, SUM (order_items.item_price*order_items.quantity) as revenue, RANK() OVER (PARTITION BY restaurants.city ORDER BY SUM(order_items.item_price * order_items.quantity) DESC)FROM restaurants INNER JOIN orders ON  restaurants.restaurant_id=orders.restaurant_id INNER JOIN order_items ON order_items.order_id=orders.order_id GROUP BY restaurants.city,restaurants.restaurant_name;

-- 28. Find the Top 3 restaurants in each city.

 SELECT city,restaurant_name,revenue, revenue_rank FROM(SELECT restaurants.city,restaurants.restaurant_name, SUM (order_items.item_price*order_items.quantity) as revenue, RANK() OVER (PARTITION BY restaurants.city ORDER BY SUM(order_items.item_price * order_items.quantity) DESC) AS revenue_rank FROM restaurants INNER JOIN orders ON  restaurants.restaurant_id=orders.restaurant_id INNER JOIN order_items ON order_items.order_id=orders.order_id GROUP BY restaurants.city,restaurants.restaurant_name ) AS ranked_restaurants WHERE revenue_rank <=3 ORDER BY city,revenue_rank;

 -- 29. Find the percentage contribution of each restaurant to total revenue.
WITH restaurants_data AS (SELECT restaurants.restaurant_name,sum(order_items.item_price*order_items.quantity) as total_revenue FROM restaurants INNER JOIN orders ON restaurants.restaurant_id=orders.restaurant_id INNER JOIN order_items ON order_items.order_id=orders.order_id GROUP BY restaurants.restaurant_name) SELECT restaurant_name,total_revenue,sum(total_revenue) OVER() AS overall_revenue, total_revenue * 100/sum(total_revenue) OVER() AS percentage FROM restaurants_data;

 Calculate month-over-month revenue.
