import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
import matplotlib.pyplot as plt
import numpy as np

load_dotenv()

connection_url = URL.create(
    drivername="mysql+mysqlconnector",
    username=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"),
    host=os.getenv("MYSQL_HOST"),
    port=int(os.getenv("MYSQL_PORT", 3306)),
    database=os.getenv("MYSQL_DATABASE")
)

engine = create_engine(connection_url)

tables=["suppliers","stores","products","employees","sales","inventory","returns","expenses"]

for table in tables:
    query=f"SELECT *FROM {table}"
    df=pd.read_sql(query,engine)
    print(f"\n{"="*100}")
    print(f"{table.upper()} Table")
    print(df)

# Q1. Find the total number of stores operating in the company.

query_1="SELECT count(store_name)  FROM stores;"
df=pd.read_sql(query_1,engine)
print("total number of stores operating inthe company:",df.iloc[0,0])

# Q2. Find the total number of products available.

query_2="SELECT count(product_name) FROM products;"
df=pd.read_sql(query_2,engine)
print("total number of products available:",df.iloc[0,0])

# Q3. Find the total number of employees.

query_3="SELECT count(employee_id) FROM employees;"
df=pd.read_sql(query_3,engine)
print("total number of employees:",df.iloc[0,0])

# Q4. Find the total number of sales transactions.

query_4="SELECT count(sale_id) FROM sales;"
df=pd.read_sql(query_4,engine)
print("total number of sales transactions:",df.iloc[0,0])

# Q5. Calculate the total quantity of products sold.

query_5="SELECT sum(quantity) FROM sales;"
df=pd.read_sql(query_5,engine)
print("total quantiy of products sold:",df.iloc[0,0])

# Q6. Calculate the total revenue generated by the company.

QUERY_6="SELECT sum(quantity*selling_price) FROM sales;"
df=pd.read_sql(QUERY_6,engine)
print("total revenue:",df.iloc[0,0])

# Q7. Calculate the total discount given to customers.

query_7="SELECT sum(discount) FROM sales;"
df=pd.read_sql(query_7,engine)
print(" total discount given to customers:",df.iloc[0,0])

# Q8. Calculate the total expenses incurred by all stores.

query_8="SELECT sum(expense_amount) FROM expenses;"
df=pd.read_sql(query_8,engine)
print("total expenses incurred by all store:",df.iloc[0,0])

# Q9. Find the total number of returned products.

query_9="SELECT sum(return_quantity) FROM returns;"
df=pd.read_sql(query_9,engine)
print("total number of returned products:",df.iloc[0,0])

# Q10. Find the number of sales transactions for each payment method.

query_10="SELECT payment_method ,COUNT(*) AS number_of_sales  FROM sales GROUP BY payment_method;"
df=pd.read_sql(query_10,engine)
print("number of sales transactions for each payment method:",df)

plt.figure()
bars=plt.bar(df["payment_method"],df["number_of_sales"],color="black")
plt.xlabel("Payment method")
plt.ylabel("Number of Sales")
plt.title("Number of Sales Transactions by Payment Method")
plt.bar_label(bars)
plt.tight_layout()
plt.show()

# Q11. Find the total revenue generated by each store.

QUERY_11="SELECT store_name,SUM(quantity*selling_price) AS total_revenue FROM sales INNER JOIN stores ON stores.store_id =sales.store_id GROUP BY store_name;"
df=pd.read_sql(QUERY_11,engine)
print("total revenue by each store",df)

plt.figure()
df.plot.bar(x="store_name",y="total_revenue",color="green")
plt.xlabel("Store Name")
plt.ylabel("Total Revenue")
plt.title("Total Revenue by each Store")
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q12. Find the total quantity sold by each store.

QUERY_12="SELECT store_name ,SUM(quantity)  AS total_quantity FROM sales INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY store_name; "
df=pd.read_sql(QUERY_12,engine)
print("total quantity sold by each store:",df)

plt.figure()
bars=plt.bar(df["store_name"],df["total_quantity"],color="lavender")
plt.xlabel("store name")
plt.ylabel("total Quantity")
plt.title("total quantity sold by ech store")
plt.bar_label(bars)
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q13. Find the average transaction value for each store.

QUERY_13="SELECT store_name,AVG(quantity*selling_price) AS average FROM sales INNER JOIN stores ON stores.store_id =sales.store_id GROUP BY store_name;"
df=pd.read_sql(QUERY_13,engine)
print("Average transaction value for each store",df)

plt.figure()
bars=plt.bar(df["store_name"],df["average"],color="skyblue")
plt.xlabel("Store Name")
plt.ylabel("Average trasaction")
plt.title("Average transaction  by each Store")
plt.bar_label(bars)
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q14. Find the total revenue generated by each product category.

query_14="SELECT category,SUM(quantity*sales.selling_price) AS total_revenue FROM sales INNER JOIN products ON  products.product_id=sales.product_id GROUP BY products.category;"
df=pd.read_sql(query_14,engine)
print("total revenue generate by each product category",df)

plt.figure()
bars=plt.bar(df["category"],df["total_revenue"],color="grey")
plt.xlabel("Ctegory")
plt.ylabel("total revenue")
plt.title("total revenue generated by each product category")
plt.bar_label(bars)
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q15. Find the total quantity sold by each product category.

query_15="SELECT products.category,SUM(quantity) AS total_quantity FROM sales INNER JOIN products ON products.product_id=sales.product_id GROUP BY products.category; "
df=pd.read_sql(query_15,engine)
print("total quantity sold by each category",df)

plt.figure()
bars=plt.bar(df["category"],df["total_quantity"],color="aquamarine")
plt.xlabel("Category")
plt.ylabel("total quantity")
plt.title("total aquantity sold by  each product category")
plt.bar_label(bars)
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q16. Identify the products generating the highest revenue.

QUERY_16="SELECT products.product_name,SUM(quantity*sales.selling_price) AS total_revenue FROM sales INNER JOIN products ON products.product_id=sales.product_id GROUP BY products.product_name ORDER BY total_revenue DESC ;"
df=pd.read_sql(QUERY_16,engine)
print("products generating the highest revenue:",df.iloc[0])
plt.figure(figsize=(12,6))
bars=plt.bar(df["product_name"],df["total_revenue"],color="moccasin")
plt.xlabel("Product Name")
plt.ylabel("total revenue")
plt.title("products generating the highest revenue")
plt.bar_label(bars)
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q17. Identify products with high sales quantity but relatively low revenue.

query_17='WITH products_total AS (SELECT products.product_name,SUM(sales.quantity) AS total_quantity , sum(quantity*sales.selling_price) AS total_revenue FROM sales INNER JOIN products ON products.product_id=sales.product_id GROUP BY products.product_name ORDER BY products.product_name)SELECT product_name,total_quantity,total_revenue FROM products_total WHERE total_quantity>(SELECT AVG(total_quantity) FROM products_total) AND total_revenue<(SELECT AVG(total_revenue) FROM products_total) ;'
df=pd.read_sql(query_17,engine)
print("products with high sales quantity but relatively low revenue.",df)

plt.figure(figsize=(10, 6))

plt.scatter(df["total_quantity"],df["total_revenue"],color="black")
plt.xlabel("Total Quantity Sold")
plt.ylabel("Total Revenue")
plt.title("High Quantity but Relatively Low Revenue Products")
plt.ticklabel_format(style="plain", axis="both")
plt.tight_layout()
plt.show()

# Q18. Calculate the company's overall average selling price.

query_18="SELECT AVG(selling_price) FROM sales;"
df=pd.read_sql(query_18,engine)
print("company's overall average selling price:",df.iloc[0,0])

# Q19. Calculate revenue generated from discounted transactions.

query_19="SELECT sum(quantity*selling_price) AS revenue FROM sales WHERE discount >0;"
df=pd.read_sql(query_19,engine)
print("revenue generated from discounted transactions:",df.iloc[0,0])

# Q20. Compare discounted sales with non-discounted sales.

QUERY_20="SELECT CASE WHEN discount > 0 THEN 'Discounted' ELSE 'Non_Discounted' END AS sales_type ,COUNT(*)  AS no_of_sales FROM sales GROUP BY sales_type;"
df=pd.read_sql(QUERY_20,engine)
print("Compare discounted sales with non-discounted sales:",df)

plt.figure(figsize=(7,5))

bars = plt.bar(df["sales_type"],df["no_of_sales"],color="skyblue")
plt.xlabel("Sale Type")
plt.ylabel("Number of Sales")
plt.title("Discounted vs Non-Discounted Sales")
plt.bar_label(bars)
plt.tight_layout()
plt.show()

# Q21. Find the monthly revenue generated by the company.

query_21="SELECT DATE_FORMAT(sale_date,'%Y-%M')AS month , sum(quantity*selling_price) AS monthy_revenue FROM sales GROUP BY DATE_FORMAT(sale_date,'%Y-%M')ORDER BY month;"
df=pd.read_sql(query_21,engine)
print("monthly revenue ",df)
plt.figure(figsize=(7,5))

plt.plot(df["month"],df["monthy_revenue"],color="skyblue",marker="s",linestyle=":")
plt.xlabel("month name")
plt.ylabel("month revenue")
plt.title("month revenue by the company")

plt.tight_layout()
plt.show()


# Q22. Identify months in which revenue changed significantly compared with the previous month.

query_22="SELECT sale_date , quantity,selling_price FROM sales;"
df=pd.read_sql(query_22,engine)
df["date_sale"]=pd.to_datetime(df["sale_date"])
df["months"]=df["date_sale"].dt.month
df["revenue"] = df["quantity"] * df["selling_price"]
month=df.groupby("months")["revenue"].sum()
month.index = month.index.map({
    1: "January",
    2: "February",
    3: "March"
})
print("Monthly Revenue:",month)
percentage_change = month.pct_change() * 100
print("Percentage Change:",percentage_change)

plt.figure(figsize=(8,5))

plt.plot(percentage_change.index,percentage_change.values,marker="o")
plt.xlabel("Month")
plt.ylabel("Percentage Change (%)")
plt.title("Monthly Revenue Percentage Change")
plt.grid()
plt.tight_layout()
plt.show()

# Q23. Find the yearly revenue trend.
# “Not applicable with current sample data.”

#24. Find the contribution of each category to total company revenue.

query_24="SELECT category,SUM(quantity*sales.selling_price) AS total_revenue FROM sales INNER JOIN products ON  products.product_id=sales.product_id GROUP BY products.category;"
df=pd.read_sql(query_24,engine)
df["contribution"]=(df["total_revenue"]/df["total_revenue"].sum())*100
print("total revenue generate by each product category",df)

plt.figure()
plt.pie(df["contribution"],labels=df["category"],autopct="1.1f%%")
plt.title("Contribution of Each Category to Total Revenue")
plt.show()

# Q25. Compare all stores based on total revenue.

query_25="SELECT stores.store_name , sum(quantity*sales.selling_price) AS total_revenue FROM sales INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY store_name;"
df=pd.read_sql(query_25,engine)
print("copmare all stores based on total revenue:",df)

plt.figure()
df.plot.bar(x="store_name",y="total_revenue")
plt.xlabel("store name")
plt.ylabel("Total Revenue")
plt.title("Compare all stores based on total revenue")
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q26. Compare stores based on total quantity sold.

query_26="SELECT stores.store_name , sum(quantity) AS total_quantity FROM sales INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY store_name;"
df=pd.read_sql(query_26,engine)
print("Compare stores based on total quantity sold:",df)

plt.figure()
df.plot.bar(x="store_name",y="total_quantity")
plt.xlabel("store name")
plt.ylabel("Total quantity")
plt.title("Compare all stores based on total quantity sold")
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q27. Calculate average revenue per transaction for each store.

query_27="SELECT stores.store_name , AVG(quantity*sales.selling_price) AS average FROM sales INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY store_name;"
df=pd.read_sql(query_27,engine)
print("average revenue per transaction for each store:",df)


plt.figure()
df.plot.bar(x="store_name",y="average")
plt.xlabel("store name")
plt.ylabel("average")
plt.title("average revenue per transaction for each store.")
plt.ticklabel_format(style="plain", axis="y")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q28. Compare store expenses with store revenue.

query_28=" WITH store_expense AS(SELECT store_id ,sum(expense_amount) AS total_expense FROM expenses GROUP BY store_id),store_revenue AS( SELECT store_id ,sum(quantity*selling_price) AS total_revenue  FROM sales GROUP BY store_id ) SELECT stores.store_name,store_expense.total_expense , store_revenue.total_revenue FROM stores INNER JOIN store_expense ON stores.store_id=store_expense.store_id INNER JOIN store_revenue ON stores.store_id=store_revenue.store_id;"
df=pd.read_sql(query_28,engine)
print("Compare store expenses with store revenue",df)

plt.figure()
x=np.arange(len(df))
width=0.35
plt.bar(x-width/2,df["total_expense"],width,label="total_expense")
plt.bar(x+width/2,df["total_revenue"],width,label="total_revenue")
plt.xticks(x,df['store_name'],rotation=45,ha="right")
plt.legend()
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()


# Q29. Calculate the profit contribution of each store.

query_29=" WITH store_expense AS(SELECT store_id ,sum(expense_amount) AS total_expense FROM expenses GROUP BY store_id),store_revenue AS( SELECT store_id ,sum(quantity*selling_price) AS total_revenue  FROM sales GROUP BY store_id ) SELECT stores.store_name,store_expense.total_expense , store_revenue.total_revenue ,(store_revenue.total_revenue - store_expense.total_expense ) AS profit FROM stores INNER JOIN store_expense ON stores.store_id=store_expense.store_id INNER JOIN store_revenue ON stores.store_id=store_revenue.store_id;"
df=pd.read_sql(query_29,engine)
print("profit contribution of each store:",df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

bars = plt.bar(df["store_name"],df["profit"],color="skyblue")
plt.bar_label(bars)
plt.xlabel("Store")
plt.ylabel("Profit")
plt.title("Profit Generated by Each Store")
plt.ticklabel_format(style="plain",axis="y")
plt.axhline(0, color="black")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# Q30. Identify stores where revenue is high but profit is relatively low.

query_30=" WITH store_expense AS(SELECT store_id ,sum(expense_amount) AS total_expense FROM expenses GROUP BY store_id),store_revenue AS( SELECT store_id ,sum(quantity*selling_price) AS total_revenue  FROM sales GROUP BY store_id ),store_profit AS (SELECT stores.store_name,store_expense.total_expense , store_revenue.total_revenue ,(store_revenue.total_revenue - store_expense.total_expense ) AS profit FROM stores INNER JOIN store_expense ON stores.store_id=store_expense.store_id INNER JOIN store_revenue ON stores.store_id=store_revenue.store_id) SELECT * FROM store_profit WHERE total_revenue >(SELECT AVG(total_revenue) FROM store_profit)AND profit <(SELECT AVG(profit) FROM store_profit) ;"
df=pd.read_sql(query_30,engine)
print("stores where revenue is high but profit is relatively low",df)

plt.figure(figsize=(8, 5))
bars = plt.bar(df["store_name"],df["profit"])
plt.bar_label(bars)
plt.axhline(0, color="black")
plt.xlabel("Store")
plt.ylabel("Profit")
plt.title("High Revenue but Relatively Low Profit")
plt.tight_layout()
plt.show()

# Q31. Identify stores with relatively high expenses compared with revenue.

query_31=" WITH store_expense AS(SELECT store_id ,sum(expense_amount) AS total_expense FROM expenses GROUP BY store_id),store_revenue AS( SELECT store_id ,sum(quantity*selling_price) AS total_revenue  FROM sales GROUP BY store_id ) , store_analysis AS (SELECT stores.store_name,store_expense.total_expense , store_revenue.total_revenue, store_expense.total_expense / store_revenue.total_revenue AS expense_ratio FROM stores INNER JOIN store_expense ON stores.store_id=store_expense.store_id INNER JOIN store_revenue ON stores.store_id=store_revenue.store_id) SELECT * FROM store_analysis ORDER BY expense_ratio DESC;"
df=pd.read_sql(query_31,engine)
print("stores with relatively high expenses compared with revenue",df)

plt.figure()
df.plot.bar(x="store_name",y="expense_ratio")
plt.xlabel("store_name")
plt.ylabel("expanse ratio")
plt.title("stores with relatively high expenses compared with revenue")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q32. Analyze monthly revenue for each store.

query_32="SELECT store_name,DATE_FORMAT(sale_date,'%Y-%M') AS month ,sum(quantity*sales.selling_price) AS revenue FROM sales INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY store_name,DATE_FORMAT(sale_date,'%Y-%M') ;"
df=pd.read_sql(query_32,engine)
print("monthly revenue fore each store",df)


plt.figure()
for store in df["store_name"].unique():
    store_data=df[df["store_name"]==store]

    plt.plot(store_data["month"],store_data["revenue"],marker="o",label=store)
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.title("Monthly Revenue by Store")
plt.legend()
plt.xticks(rotation=45)
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q33. Identify the best-selling product in each store.

query_33="SELECT sum(sales.quantity) AS total_quantity,products.product_name, stores.store_name  FROM stores INNER JOIN sales ON stores.store_id=sales.store_id INNER JOIN products ON products.product_id= sales.product_id GROUP BY stores.store_name,products.product_name  ORDER BY total_quantity DESC; "
df=pd.read_sql(query_33,engine)
print("best-selling product in each store", df)

plt.figure(figsize=(10,5))
df["store_product"]=df["store_name"]+"-"+df["product_name"]
df.plot.bar(x="store_product",y="total_quantity")
plt.xlabel("store name")
plt.ylabel("total quantity")
plt.title("selling product in each store")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q34. Identify stores showing consistent growth over multiple months.

query_34="SELECT stores.store_name,DATE_FORMAT(sale_date,'%y-%m') AS momth , SUM(quantity*selling_price) AS revenue  FROM sales INNER JOIN stores ON stores.store_id=sales.store_id  GROUP BY stores.store_name, DATE_FORMAT(sale_date,'%y-%m') ;"
df=pd.read_sql(query_34,engine)
print(df)

# Q35. Calculate total stock received for each product.

query_35="SELECT sum(inventory.stock_received) AS total, products.product_name FROM inventory INNER JOIN products ON products.product_id=inventory.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_35,engine)
print("total stock received for each product",df)

plt.figure()
df.plot.bar(x="product_name",y="total")
plt.xlabel("Product Name")
plt.ylabel("Total Stock Received")
plt.title("total stock received for each product")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q36. Calculate total stock sold for each product.

query_36="SELECT sum(inventory.stock_sold) AS total, products.product_name FROM inventory INNER JOIN products ON products.product_id=inventory.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_36,engine)
print("total stock sold for each product",df)

plt.figure()
df.plot.bar(x="product_name",y="total")
plt.xlabel("Product Name")
plt.ylabel("Total Stock sold")
plt.title("total stock sold for each product")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q37. Calculate total damaged stock for each product.

query_37="SELECT sum(inventory.stock_damaged) AS total, products.product_name FROM inventory INNER JOIN products ON products.product_id=inventory.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_37,engine)
print("total stock damaged for each product",df)

plt.figure()
df.plot.bar(x="product_name",y="total")
plt.xlabel("Product Name")
plt.ylabel("Total Stock damaged")
plt.title("total stock damaged for each product")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q38. Find products with the highest amount of damaged inventory.

query_38="SELECT sum(inventory.stock_damaged) AS total, products.product_name FROM inventory INNER JOIN products ON products.product_id=inventory.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_38,engine)

high=df["total"].max()
dam_high=df[df["total"]==high]
print("products with the highest amount of damaged inventory:",dam_high)

# Q39. Calculate remaining inventory for each store-product combination.

query_39="SELECT stores.store_name,products.product_name,sum(inventory.stock_received) AS total_received , sum(inventory.stock_sold) AS total_sold , SUM(inventory.stock_damaged) AS total_damaged, sum(inventory.stock_received)-sum(inventory.stock_sold)  - SUM(inventory.stock_damaged) AS remaining FROM inventory INNER JOIN  stores ON stores.store_id=inventory.store_id INNER JOIN products ON products.product_id=inventory.product_id GROUP BY stores.store_name, products.product_name;"
df=pd.read_sql(query_39,engine)
print(df)

plt.figure()
for store in df["store_name"].unique():
    store_data=df[df["store_name"]==store]

    plt.plot(store_data["product_name"],store_data["remaining"],label=store,marker="s")
plt.xlabel("product name")
plt.ylabel("remaining number")
plt.title("remaining inventory for each store-product combination")
plt.xticks(rotation=45,ha="right")
plt.legend()
plt.tight_layout()
plt.show()
    
# Q40. Identify products with very low remaining stock.

query_40="SELECT products.product_name,sum(inventory.stock_received) AS total_received , sum(inventory.stock_sold) AS total_sold , SUM(inventory.stock_damaged) AS total_damaged, sum(inventory.stock_received)-sum(inventory.stock_sold)  - SUM(inventory.stock_damaged) AS remaining FROM inventory INNER JOIN products ON products.product_id=inventory.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_40,engine)
low=df["remaining"].min()
pro_low=df[df["remaining"]==low]
print("products with very low remaining stock",pro_low)

plt.figure()
df.plot.bar(x="product_name",y="remaining")
plt.xlabel("product name")
plt.ylabel("remaining name")
plt.title("product remaining stock")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q41. Identify products where stock received is high but sales are low.

query_41="SELECT products.product_name,inventory.stock_received,inventory.stock_sold FROM inventory INNER JOIN products ON products.product_id=inventory.product_id WHERE inventory.stock_received >(SELECT AVG(stock_received )FROM inventory) AND inventory.stock_sold <(SELECT AVG(stock_sold )FROM inventory) ;"
df=pd.read_sql(query_41,engine)
print(df)

# Q42. Identify products where demand is high but available stock is low.

query_42="SELECT products.product_name,inventory.stock_received,inventory.stock_sold,inventory.stock_damaged FROM inventory INNER JOIN products ON products.product_id=inventory.product_id;"
df=pd.read_sql(query_42,engine)

df["available"]=(df["stock_received"]-df["stock_sold"]-df["stock_damaged"])
avg_dem=df["stock_sold"].mean()
avg_available=df["available"].mean()
result=df[(df["stock_sold"]>avg_available) & (df["available"]<avg_available)]
print("products where demand is high but available stock is low",result)

# Q43. Compare inventory movement across different stores.

query_43="SELECT stores.store_name,sum(inventory.stock_received) AS total_received,sum(inventory.stock_sold) AS total_sold,sum(inventory.stock_damaged)AS total_damaged FROM inventory INNER JOIN stores ON stores.store_id=inventory.store_id GROUP BY stores.store_name;"
df=pd.read_sql(query_43,engine)
print("Compare inventory movement across different stores",df)

x = np.arange(len(df))
width = 0.25

plt.figure(figsize=(12, 6))
plt.bar(x - width, df["total_received"], width, label="Received")
plt.bar(x, df["total_sold"], width, label="Sold")
plt.bar(x + width, df["total_damaged"], width, label="Damaged")
plt.xlabel("Store")
plt.ylabel("Number of Units")
plt.title("Inventory Movement Across Stores")
plt.xticks(x, df["store_name"], rotation=45, ha="right")
plt.legend()
plt.tight_layout()
plt.show()

# Q44. Analyze how inventory levels change over time.

query_44="SELECT DATE_FORMAT(inventory_date,'%y-%m') AS month , sum(stock_received) AS total_received,sum(stock_sold) AS total_sold,sum(stock_damaged)AS total_damaged FROM inventory GROUP BY DATE_FORMAT(inventory_date,'%y-%m');"
df=pd.read_sql(query_44,engine)
print("inventory levels change over time",df)

plt.figure(figsize=(10, 5))

plt.plot(df["month"], df["total_received"], marker="o", label="Received")
plt.plot(df["month"], df["total_sold"], marker="o", label="Sold")
plt.plot(df["month"], df["total_damaged"], marker="o", label="Damaged")
plt.xlabel("Month")
plt.ylabel("Number of Units")
plt.title("Inventory Levels Over Time")
plt.legend()
plt.grid()
plt.tight_layout()
plt.show()

# Q45. Identify products that may require increased inventory planning.

query_45 = "SELECT products.product_name,SUM(inventory.stock_received) AS total_received,SUM(inventory.stock_sold) AS total_sold,SUM(inventory.stock_damaged) AS total_damaged FROM inventory INNER JOIN products ON products.product_id = inventory.product_id GROUP BY products.product_name;"
df = pd.read_sql(query_45, engine)

df["consumption_rate"] = (df["total_sold"] / df["total_received"]) * 100
avg_consumption = df["consumption_rate"].mean()
result = df[df["consumption_rate"] > avg_consumption]
print("Products that may require increased inventory planning:")
print(result)

# Q46. Calculate the return rate for each product.

query_46="SELECT products.product_name,returns.return_quantity, inventory.stock_sold FROM returns INNER JOIN products ON products.product_id=returns.product_id INNER JOIN inventory ON inventory.product_id=returns.product_id;"
df=pd.read_sql(query_46,engine)

df=df.groupby("product_name").agg(
    total_retured=("return_quantity","sum"),
    total_sold=("stock_sold","sum")
)
df["return_rate"]=(df["total_retured"]/df["total_sold"])*100
print("return rate for each product",df)

# Q47. Find categories having higher return activity.

query_47="SELECT products.category, returns.return_quantity FROM returns INNER JOIN products ON  products.product_id=returns.product_id;"
df=pd.read_sql(query_47,engine)

max_ret=df.groupby("category")["return_quantity"].sum()
high_ret=max_ret[max_ret==max_ret.max()]
print(high_ret)

# Q48. Analyze the major reasons for product returns.

query_48="SELECT return_reason FROM returns;"
df=pd.read_sql(query_48,engine)
high=df["return_reason"].value_counts()
high_res=high.idxmax()
print("major reasons for product returns:",high_res)

# Q49. Identify products with high sales and high return rates.

query_49="SELECT products.product_name,sales.selling_price,sales.quantity ,returns.return_quantity,inventory.stock_sold FROM returns INNER JOIN inventory ON inventory.product_id=returns.product_id INNER JOIN sales ON sales.product_id=returns.product_id INNER JOIN products ON products.product_id=returns.product_id; "
df=pd.read_sql(query_49,engine)

df["sales"]=df["selling_price"]*df["quantity"]
df=df.groupby("product_name").agg(
    total_quantity=("return_quantity","sum"),
    total_sold=("stock_sold","sum"),
    total_sales=("sales","sum")
)
df['return_rate']=(df["total_quantity"]/df["total_sold"])*100
high_rate=df['return_rate']>df['return_rate'].mean()
high_sales=df['total_sales']>df["total_sales"].mean()
pro=df[high_rate & high_sales]
print("products with high sales and high return rates",pro)

# Q50. Compare return rates across stores.

query_50="SELECT stores.store_name,SUM(returns.return_quantity) AS total_qua,SUM(inventory.stock_sold) AS total_sto FROM returns INNER JOIN inventory ON inventory.store_id=returns.store_id INNER JOIN  stores ON stores.store_id=returns.store_id GROUP BY stores.store_name; "
df=pd.read_sql(query_50,engine)

df['return_rate']=(df["total_qua"]/df["total_sto"])*100
print("Compare return return accross stores",df[["return_rate","store_name"]])

# Q51. Analyze monthly return trends.

query_51 = "SELECT DATE_FORMAT(return_date, '%Y-%M') AS month,SUM(return_quantity) AS total_returns FROM returns GROUP BY DATE_FORMAT(return_date, '%Y-%M') ORDER BY month;"

df = pd.read_sql(query_51, engine)

print("monthly return trends.",df)

# Q52. Find whether products with higher discounts also experience higher returns.

query_52="SELECT products.product_name,AVG(sales.discount) AS avg_discounts,SUM(returns.return_quantity) AS total_returns FROM returns INNER JOIN sales ON sales.product_id=returns.product_id INNER JOIN products ON products.product_id=returns.product_id GROUP BY products.product_name;"
df=pd.read_sql(query_52,engine)

high_discount = df["avg_discounts"] > df["avg_discounts"].mean()

high_returns = df["total_returns"] > df["total_returns"].mean()

hig = df[high_discount & high_returns]

print("products with higher discounts also experience higher returns",hig)

# Q53. Calculate total sales handled by each employee.

query_53="SELECT employee_id,employee_name,monthly_salary FROM employees  GROUP BY employee_id;"
df=pd.read_sql(query_53,engine)
print("emolyees salary:",df)

# Q54. Calculate total revenue generated through each employee's transactions.

query_54="SELECT employees.employee_name,SUM(sales.quantity*sales.selling_price) AS revenue FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id GROUP BY employees.employee_name;"
df=pd.read_sql(query_54,engine)
print("total revenue generated through each employee's transactions",df)

# Q55. Calculate average transaction value for each employee.

query_55="SELECT employees.employee_name,AVG(sales.quantity*sales.selling_price) AS revenue FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id GROUP BY employees.employee_name;"
df=pd.read_sql(query_55,engine)
print("average transaction value for each employee",df)

# Q56. Compare employee sales performance within the same store.

query_56="SELECT stores.store_name,employees.employee_name,SUM(sales.quantity*sales.selling_price) AS revenue FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id INNER JOIN stores ON stores.store_id=sales.store_id GROUP BY stores.store_name,employees.employee_name;"
df=pd.read_sql(query_56,engine)
print("Compare employee sales performance within the same store",df)

plt.figure()
df["store_employee"]=df["store_name"]+"-"+df["employee_name"]
df.plot.bar(x="store_employee",y="revenue")
plt.xlabel("store_name with employee name")
plt.ylabel("revenue")
plt.title("employee sales performance within the same store")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q57. Identify employees handling a large number of transactions.

query_57="SELECT COUNT(employees.employee_id) AS no_of_tra,employees.employee_name FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id GROUP BY employees.employee_id,employees.employee_name ORDER BY no_of_tra DESC;"
df=pd.read_sql(query_57,engine)
print("employees handling a large number of transactions",df)

# Q58. Compare employee salary with the revenue generated through their sales.

query_58="SELECT employees.employee_name,sum(sales.quantity*sales.selling_price) AS revenue , employees.monthly_salary FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id GROUP BY employees.employee_name,employees.monthly_salary;"
df=pd.read_sql(query_58,engine)
print("comployee salary with the revenue generated through their sales",df)

plt.figure()
df["name_salary"]=df["employee_name"]+"-"+df["monthly_salary"].astype(str)
df.plot.bar(x="name_salary",y="revenue")
plt.xlabel("employee name with salary")
plt.ylabel("employee revenue")
plt.title("Compare employee salary with the revenue generated through their sales")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()
# Q59. Identify employees with high sales contribution relative to their salary cost.

query_59="SELECT employees.employee_name,sales.quantity,sales.selling_price, employees.monthly_salary FROM sales INNER JOIN employees ON employees.employee_id=sales.employee_id;"
df=pd.read_sql(query_59,engine)

df["revenue"]=df['quantity']*df["selling_price"]
employee=df.groupby("employee_name").agg(
    rev=("revenue",'sum'),
    salary_cost=("monthly_salary","first")
)
ratio=employee["rev"]/employee["salary_cost"]
high = ratio[ratio > ratio.mean()]
print("employees with high sales contribution relative to their salary cost",high)

# Q60. Analyze employee performance across different stores.

query_60="SELECT employees.employee_name,stores.store_name,SUM(sales.quantity*sales.selling_price) AS total_revenue ,COUNT(sales.sale_id) AS total_transaction FROM employees INNER JOIN sales ON employees.employee_id=sales.employee_id INNER JOIN stores ON stores.store_id=employees.store_id GROUP BY stores.store_id,stores.store_name,employees.employee_id,employees.employee_name;"
df=pd.read_sql(query_60,engine)
print("employee performance across different stores",df)

# Q61. Compare suppliers based on supplier rating.

query_61="SELECT supplier_name , supplier_rating FROM suppliers;"
df=pd.read_sql(query_61,engine)
print("suppliers based on supplier rating",df)

# Q62. Find how many products are supplied by each supplier.

query_62="SELECT suppliers.supplier_name,count(products.product_id) AS total_product FROM products INNER JOIN suppliers ON products.supplier_id=suppliers.supplier_id GROUP BY suppliers.supplier_id;"
df=pd.read_sql(query_62,engine)
print("products are supplied by each supplier",df)

plt.figure()
df.plot.bar(x="supplier_name",y="total_product")
plt.xlabel("supplier name")
plt.ylabel("no_of_product")
plt.title("products are supplied by each supplier")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q63. Compare product costs across suppliers.

query_63="SELECT suppliers.supplier_name,products.product_name,products.cost_price FROM products INNER JOIN  suppliers ON suppliers.supplier_id=products.supplier_id ;"
df=pd.read_sql(query_63,engine)
print("product costs across suppliers",df)

# Q64. Identify suppliers associated with products having high damage rates.

query_64="SELECT suppliers.supplier_name,products.product_name,inventory.stock_received,inventory.stock_damaged FROM products INNER JOIN suppliers ON suppliers.supplier_id=products.supplier_id INNER JOIN inventory ON inventory.product_id=products.product_id;"
df=pd.read_sql(query_64,engine)

df["damage_rate"]=(df["stock_damaged"]/df["stock_received"])*100
max_damage = df["damage_rate"].max()
highest_damage = df[df["damage_rate"] == max_damage]
print(highest_damage[["supplier_name", "product_name", "damage_rate"]])

# Q65. Analyze whether supplier rating has any relationship with product performance.

query_65='SELECT suppliers.supplier_name,suppliers.supplier_rating,products.product_name,SUM(sales.quantity * sales.selling_price) AS total_revenue FROM suppliers INNER JOIN products ON suppliers.supplier_id = products.supplier_id INNER JOIN sales ON products.product_id = sales.product_id GROUP BY suppliers.supplier_id,suppliers.supplier_name,suppliers.supplier_rating,products.product_id,products.product_name;'
df=pd.read_sql(query_65,engine)
print("supplier rating has any relationship with product performance",df)

plt.figure()
plt.scatter(df["supplier_rating"], df["total_revenue"])
plt.xlabel("Supplier Rating")
plt.ylabel("Total Revenue")
plt.title("Supplier Rating vs Product Performance")
plt.show()

# Q66. Identify suppliers associated with products having high return rates.

query_66='SELECT suppliers.supplier_name, products.product_name,   inventory.stock_sold,   returns.return_quantity FROM products INNER JOIN suppliers ON suppliers.supplier_id = products.supplier_id INNER JOIN inventory ON inventory.product_id = products.product_id INNER JOIN returns ON returns.product_id = products.product_id;'
df=pd.read_sql(query_66,engine)

df["return_rate"] = (df["return_quantity"] / df["stock_sold"]) * 100
max_return_rate = df["return_rate"].max()
highest = df[df["return_rate"] == max_return_rate]
print(highest[["supplier_name", "product_name", "return_rate"]])

# Q67. Calculate product-level profit.

query_67="SELECT products.product_name,sales.quantity,sales.selling_price, products.cost_price AS cost_price FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_67,engine)

df["revenue"]=df["quaantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
profit_pro=df.groupby("product_name")["profit"].sum()
print("product-level profit",profit_pro)

plt.figure()
profit_pro.plot.bar(x="product_name",y="profit")
plt.xlabel("product_name")
plt.ylabel("profit_product")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q68. Calculate category-level profit.

query_68="SELECT products.category,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_68,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
profit_cate=df.groupby("category")["profit"].sum()
print("category level profit",profit_cate)

plt.figure()
profit_cate.plot.bar(x="category",y="profit")
plt.xlabel("product_name")
plt.ylabel("profit_category")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q69. Calculate store-level profit.

query_69="SELECT stores.store_name,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN stores ON stores.store_id=sales.store_id INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_69,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit_sto']=df["revenue"]-df["total_cost"]
profit_store=df.groupby("store_name")["profit_sto"].sum()
print("category level profit",profit_store)

plt.figure()
profit_store.plot.bar(x="store_name",y="profit_sto")
plt.xlabel("store_name")
plt.ylabel("profit_store")
plt.xticks(rotation=45,ha="right")
plt.ticklabel_format(style="plain",axis="y")
plt.tight_layout()
plt.show()

# Q70. Calculate profit margin for each product.

query_70="SELECT products.product_name,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_70,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df = df.groupby("product_name")[["profit", "revenue"]].sum()
df["profit_margine"] = (df["profit"] / df["revenue"]) * 100
print(f"profit margin for each product{df}")

plt.figure()
df["profit_margine"].plot.pie(labels=df.index,autopct="%1.1f%%")
plt.show()

# Q71. Identify products with high revenue but low profit margin.

query_71="SELECT products.product_name,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_71,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df = df.groupby("product_name")[["profit", "revenue"]].sum()
df["profit_margine"] = (df["profit"] / df["revenue"]) * 100

df["high_rev"]=df["revenue"]>df["revenue"].mean()
df["low_pro_mar"]=df["profit_margine"]<df["profit_margine"].mean()
df=df[(df["high_rev"])&(df["low_pro_mar"])]
print("products with high revenue but low profit margin",df)

# Q72. Identify products with relatively low revenue but high profit margin.

query_72="SELECT products.product_name,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_72,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df = df.groupby("product_name")[["profit", "revenue"]].sum()
df["profit_margine"] = (df["profit"] / df["revenue"]) * 100

df["high_rev"]=df["revenue"]<df["revenue"].mean()
df["low_pro_mar"]=df["profit_margine"]>df["profit_margine"].mean()
df=df[(df["high_rev"])&(df["low_pro_mar"])]
print("products with high revenue but low profit margin",df)

# Q73. Compare revenue, expenses, and profit for each store.

query_73="SELECT stores.store_name,expenses.expense_amount,sales.quantity,sales.selling_price FROM stores INNER JOIN sales ON sales.store_id=stores.store_id INNER JOIN expenses ON expenses.store_id=stores.store_id;"
df=pd.read_sql(query_73,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df=df.groupby("store_name")[["revenue","expense_amount"]].sum()
df["profit"]=df["revenue"]-df["expense_amount"]
print("Compare revenue, expenses, and profit for each store",df)

# Q74. Analyze how discount percentage affects profit margin.

query_74="SELECT sales.quantity,sales.selling_price, products.cost_price,sales.discount  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_74,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df["profit_margine"] = (df["profit"] / df["revenue"]) * 100
df=df.groupby("discount")["profit_margine"].mean()
print("discount percentage affects profit margin",df)

# Q75. Identify the major sources of company profit.

query_75="SELECT stores.store_name,products.product_name,products.category,sales.quantity,sales.selling_price,products.cost_price FROM sales INNER JOIN stores ON stores.store_id=sales.store_id INNER JOIN products ON products.product_id=sales.product_id;"
df=pd.read_sql(query_75,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df = df.groupby(["store_name", "product_name", "category"])["profit"].sum()
df = df.sort_values(ascending=False)
print("the major sources of company profit",df)

plt.figure()
df=df.reset_index()
df["major_score"]=df["store_name"]+"-"+df["product_name"]+"-"+df["category"]
df.plot.bar(x="major_score",y="profit")
plt.xlabel("company_major_sources")
plt.ylabel("profit")
plt.title("major sources of company profit")
plt.ticklabel_format(style="plain",axis="y")
plt.xticks(rotation=45,ha="right")
plt.tight_layout()
plt.show()

# Q76. Analyze the relationship between discount and quantity sold.

query_76="SELECT quantity,discount FROM sales;"
df=pd.read_sql(query_76,engine)
df=df.groupby("discount")["quantity"].sum()
print("relationship between discount and quantity sold",df)

# Q77. Analyze the relationship between selling price and quantity sold.

query_77="SELECT quantity,selling_price FROM sales;"
df=pd.read_sql(query_77,engine)
df=df.groupby("selling_price")["quantity"].sum()
print("relationship between selling_price and quantity sold",df)

# Q78. Analyze the relationship between supplier rating and product return rate.

QUERY_78="SELECT suppliers.supplier_rating,sales.quantity,returns.return_quantity FROM products INNER JOIN suppliers ON suppliers.supplier_id=products.supplier_id INNER JOIN sales ON sales.product_id=products.product_id INNER JOIN returns ON returns.product_id=products.product_id;"
df=pd.read_sql(QUERY_78,engine)

df["pro_return_rate"]=(df["return_quantity"]/df["quantity"])*100
df=df.groupby("supplier_rating")["pro_return_rate"].mean()
print(df)

# Q79. Analyze the relationship between inventory received and inventory sold.

query_79="SELECT stock_received,stock_sold FROM inventory"
df=pd.read_sql(query_79,engine)
print("relationship between inventory received and inventory sold.",df)

plt.figure()
df.plot.scatter(x="stock_received", y="stock_sold")
plt.xlabel("Inventory Received")
plt.ylabel("Inventory Sold")
plt.title("Relationship between Inventory Received and Inventory Sold")
plt.show()

# Q80. Analyze the relationship between store expenses and revenue.

query_80="SELECT stores.store_name,SUM(sales.quantity*sales.selling_price) AS revenue,SUM(expenses.expense_amount) AS expenses FROM sales INNER JOIN stores ON stores.store_id=sales.store_id INNER JOIN expenses ON expenses.store_id=stores.store_id GROUP BY stores.store_name;"
df=pd.read_sql(query_80,engine)
print("relationship between store expenses and revenue",df)

plt.figure()
df=df.reset_index()
df.plot.scatter(x="revenue",y="expenses")
for store,x,y in zip(df["store_name"],df["revenue"],df["expenses"]):
    plt.annotate(store,(x,y))
plt.xlabel("Store Expenses")
plt.ylabel("Revenue")
plt.title("Relationship between Store Expenses and Revenue")
plt.tight_layout()
plt.show() 

# Q81. Analyze the distribution of transaction values.

query_81="SELECT  quantity,selling_price FROM sales;"
df=pd.read_sql(query_81,engine)

df["transaction_value"] = df["selling_price"] * df["quantity"]
count=df["transaction_value"].value_counts(bins=10).sort_index()
print("distribution of transaction values",count)

plt.figure()
df["transaction_value"].plot.hist(bins=10)
plt.xlabel("Transaction Value")
plt.ylabel("Number of Transactions")
plt.title("Distribution of Transaction Values")
plt.ticklabel_format(style="plain",axis="y")
plt.show()

# Q82. Analyze the distribution of product profit margins.

query_82="SELECT products.product_name,sales.quantity,sales.selling_price, products.cost_price  FROM sales INNER JOIN products ON products.product_id=sales.product_id; "
df=pd.read_sql(query_82,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["total_cost"]=df["quantity"]*df["cost_price"]
df['profit']=df["revenue"]-df["total_cost"]
df["profit_margine"] = (df["profit"] / df["revenue"]) * 100
counts=df["profit_margine"].value_counts(bins=10)
print("distribution of product profit margins",counts)

plt.figure()
df["profit_margine"].plot.hist(bins=10).sort_index()
plt.xlabel("margine Value")
plt.ylabel("Number of margin")
plt.title("distribution of product profit margins.")
plt.ticklabel_format(style="plain",axis="y")
plt.show()

# Q83. Compare the spread of transaction values across stores.

query_83="SELECT stores.store_name,sales.quantity,sales.selling_price FROM sales INNER JOIN stores ON stores.store_id=sales.store_id;"
df=pd.read_sql(query_83,engine)

df["tra_value"] = df["quantity"] * df["selling_price"]

for store in df["store_name"].unique():
    print("\n", store)
    print(df[df["store_name"] == store]["tra_value"])

    df[df["store_name"] == store]["tra_value"].plot.hist(
        bins=5,
        alpha=0.5,
        label=store
    )
plt.xlabel("Transaction Value")
plt.ylabel("Number of Transactions")
plt.title("Spread of Transaction Values Across Stores")
plt.legend()
plt.show()

# Q84. Identify unusual or extreme sales transactions.

query_84="SELECT quantity,selling_price FROM sales;"
df=pd.read_sql(query_84,engine)

df["tra_value"] = df["quantity"] * df["selling_price"]
Q1 = df["tra_value"].quantile(0.25)
Q3 = df["tra_value"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR                
upper = Q3 + 1.5 * IQR
df = df[(df["tra_value"] < lower) | (df["tra_value"] > upper)]
print("Unusual or extreme sales transactions")
print("unusual or extreme sales transactions.",df)

# Q85. Identify unusual products based on sales, profit, or return behavior.

query_85="SELECT products.product_name,sales.quantity,sales.selling_price,returns.return_quantity,products.cost_price FROM products INNER JOIN sales ON products.product_id=sales.product_id INNER JOIN returns ON returns.product_id=products.product_id;"
df=pd.read_sql(query_85,engine)

df["revenue"] = df["quantity"] * df["selling_price"]
df["total_cost"] = df["quantity"] * df["cost_price"]
df["profit"] = df["revenue"] - df["total_cost"]

df=df.groupby("product_name")[["quantity","profit","return_quantity"]].sum()
print("products based on sales, profit, or return behavior.",df)

# Q86. Analyze daily sales trends.

query_86="SELECT DATE_FORMAT(sale_date,'%M-%Y') AS month,SUM(quantity) AS total FROM sales GROUP BY DATE_FORMAT(sale_date,'%M-%Y');"
df=pd.read_sql(query_86,engine)
print(" daily sales trends",df)

plt.figure()
df.plot(x="month",y="total",marker="s",linestyle="-")
plt.xlabel("Month Name")
plt.ylabel("total quantity")
plt.grid()
plt.title("daily sales trends")
plt.show()

# Q87. Analyze weekly sales patterns.

query_87 = 'SELECT WEEK(sale_date) AS week,SUM(quantity) AS sales FROM sales GROUP BY WEEK(sale_date)ORDER BY week;'
df = pd.read_sql(query_87, engine)
print(df)

plt.figure()
df.plot(x="week",y="sales",marker="o",linestyle="--")
plt.xlabel("week number")
plt.ylabel("total quantity")
plt.grid()
plt.title("WEEKLY sales trends")
plt.show()

# Q88. Analyze monthly revenue trends.

query_88="SELECT DATE_FORMAT(sale_date,'%M-%Y') AS month,SUM(quantity*selling_price) AS revenue FROM sales GROUP BY DATE_FORMAT(sale_date,'%M-%Y');"
df=pd.read_sql(query_88,engine)
print(df)

plt.figure()
df.plot(x="month",y="revenue",marker="o",linestyle=":")
plt.xlabel("Month Name")
plt.ylabel("total revenue")
plt.grid()
plt.ticklabel_format(style="plain",axis="y")
plt.title("monthly revenue trends.")
plt.tight_layout()
plt.show()

# Q89. Analyze monthly expenses.

query_89 = "SELECT DATE_FORMAT(expense_date, '%M-%Y') AS month,SUM(expense_amount) AS amount FROM expenses GROUP BY DATE_FORMAT(expense_date, '%M-%Y');"
df = pd.read_sql(query_89, engine)
print("monthly expenses.",df)

# Q90. Analyze monthly profit.

QUERY_90="SELECT sales.sale_date,sales.quantity,sales.selling_price,products.cost_price FROM sales INNER JOIN products ON products.product_id=sales.product_id;"
df=pd.read_sql(QUERY_90,engine)

df["revenue"]=df["quantity"]*df["selling_price"]
df["product_cost"]=df["quantity"]*df["cost_price"]
df["profit"]=df["revenue"]-df["product_cost"]
df["sale_date"] = pd.to_datetime(df["sale_date"])
df["month"] = df["sale_date"].dt.to_period("M")
df=df.groupby("month")["profit"].sum()
df.index = df.index.strftime("%B-%Y")

print(df)

plt.figure()
df.plot(x="month",y="profit",marker="o",linestyle=":")
plt.xlabel("Month Name")
plt.ylabel("profit")
plt.grid()
plt.ticklabel_format(style="plain",axis="y")
plt.title("monthly profit")
plt.tight_layout()
plt.show()

# Q91. Compare revenue and expenses over time.

query_91 = "SELECT DATE_FORMAT(sale_date, '%Y-%m') AS month, SUM(quantity * selling_price) AS revenue FROM sales GROUP BY DATE_FORMAT(sale_date, '%Y-%m');"
df = pd.read_sql(query_91, engine)

query_expense = "SELECT DATE_FORMAT(expense_date, '%Y-%m') AS month,SUM(expense_amount) AS expenses FROM expenses GROUP BY DATE_FORMAT(expense_date, '%Y-%m');"
df_expense = pd.read_sql(query_expense, engine)
df = df.merge(df_expense, on="month", how="left")
print("Compare revenue and expenses over time.",df)

# Q92. Identify periods of unusually high or low sales.

query_92="SELECT DATE_FORMAT(sale_date,'%Y-%M'),SUM(quantity*selling_price) AS revenue FROM sales GROUP BY DATE_FORMAT(sale_date,'%Y-%M') ;"
df=pd.read_sql(query_92,engine)

avg_revenue = df["revenue"].mean()
df["sales_status"] = "Normal"
df.loc[df["revenue"] > avg_revenue, "sales_status"] = "High"
df.loc[df["revenue"] < avg_revenue, "sales_status"] = "Low"
print("periods of unusually high or low sales.",df)

# Q93. Analyze inventory levels over time.

query_93="SELECT DATE_FORMAT(inventory_date,'%Y-%M') AS month ,SUM(stock_received) AS total_received,SUM(stock_sold) AS total_sold FROM inventory GROUP BY DATE_FORMAT(inventory_date,'%Y-%M');"
df=pd.read_sql(query_93,engine)
print("inventory levels over time",df)

plt.figure()
df.plot(x="month", y=["total_received", "total_sold"], kind="line", marker="o")
plt.xlabel("Month")
plt.ylabel("Stock Quantity")
plt.title("Inventory Trends Over Time")
plt.grid()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Q94. Analyze return trends over time.

query_94="SELECT DATE_FORMAT(return_date,'%Y-%M') AS month ,SUM(return_quantity)AS total_return FROM returns GROUP BY DATE_FORMAT(return_date,'%Y-%M');"
df=pd.read_sql(query_94,engine)
print("return trends over time",df)

plt.figure()
df.plot(x="month", y="total_return", kind="line", marker="o")
plt.xlabel("Month")
plt.ylabel("Total Return")
plt.title("Return Trends Over Time")
plt.grid()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Q95. Identify stores requiring management attention based on revenue, profit, expenses, and returns.

query_95="SELECT stores.store_id,stores.store_name,SUM(sales.quantity*sales.selling_price) AS revenue, SUM(sales.quantity*products.cost_price) AS total_cost,SUM(sales.quantity*sales.selling_price)-SUM(sales.quantity*products.cost_price) AS profit FROM stores INNER JOIN sales ON sales.store_id=stores.store_id INNER JOIN products ON sales.product_id=products.product_id GROUP BY stores.store_id, stores.store_name; "
df=pd.read_sql(query_95,engine)

query_expenses = "SELECT store_id, SUM(expense_amount) AS total_expense FROM expenses GROUP BY store_id;"
df_expenses = pd.read_sql(query_expenses, engine)

query_returns = "SELECT store_id, SUM(return_quantity) AS total_return FROM returns GROUP BY store_id;"
df_returns = pd.read_sql(query_returns, engine)

df = df.merge(df_expenses, on="store_id", how="left")
df = df.merge(df_returns, on="store_id", how="left")
df["total_expense"] = df["total_expense"].fillna(0)
df["total_return"] = df["total_return"].fillna(0)
print("stores requiring management attention based on revenue, profit, expenses, and returns.",df)

plt.figure(figsize=(10, 5))
df.plot(x="store_name",y=["revenue", "profit", "total_expense"],kind="bar")
plt.title("Store Performance Analysis")
plt.xlabel("Store")
plt.ylabel("Amount")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Q96. Identify products management should monitor based on sales, inventory, profit, and returns.

QUERY_96="SELECT products.product_id,products.product_name,SUM(sales.quantity*sales.selling_price) AS sale,SUM(inventory.stock_received)-SUM(inventory.stock_sold)-SUM(inventory.stock_damaged) AS inventory ,SUM(sales.quantity*sales.selling_price)-SUM(sales.quantity*products.cost_price) AS profit,SUM(returns.return_quantity)AS total_return FROM products INNER JOIN sales ON products.product_id=sales.product_id INNER JOIN inventory ON inventory.product_id=products.product_id INNER JOIN returns ON returns.product_id=products.product_id GROUP BY products.product_id,products.product_name;"
df=pd.read_sql(QUERY_96,engine)
print("products management should monitor based on sales, inventory, profit, and returns.",df)

plt.figure(figsize=(10, 5))
df.plot(x="product_name",y=["sale", "inventory","profit", "total_return"],kind="bar")
plt.title("Product Performance Analysis")
plt.xlabel("Product")
plt.ylabel("Amount")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Q97. Identify categories contributing significantly to overall business performance.

QUERY_97="SELECT products.category, SUM(sales.quantity * sales.selling_price) AS total_sales, SUM(sales.quantity * sales.selling_price)- SUM(sales.quantity * products.cost_price) AS total_profit FROM products INNER JOIN sales  ON products.product_id = sales.product_id GROUP BY products.category;"
df=pd.read_sql(QUERY_97,engine)
print("categories contributing significantly to overall business performance",df)

plt.figure(figsize=(10, 5))
df.plot(x="category",y=["total_sales","total_profit"],kind="bar")
plt.title("category Performance Analysis")
plt.xlabel("categoryt")
plt.ylabel("Amount")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Q98. Identify suppliers requiring further evaluation based on ratings, returns, and product performance.

query_98="SELECT supplier_id,supplier_name,suppliers.supplier_rating FROM suppliers;"
df=pd.read_sql(query_98,engine)

query_profit="SELECT products.supplier_id, SUM(sales.quantity*sales.selling_price)-SUM(sales.quantity*products.cost_price) AS profit FROM products INNER JOIN  sales ON sales.product_id=products.product_id GROUP BY products.supplier_id; ; "
df_profit=pd.read_sql(query_profit,engine)

query_return="SELECT products.supplier_id,SUM(returns.return_quantity) AS total_return FROM products INNER JOIN returns  ON returns.product_id = products.product_id GROUP BY products.supplier_id;"
df_returns = pd.read_sql(query_return, engine)

df = df.merge(df_profit, on="supplier_id", how="left")
df = df.merge(df_returns, on="supplier_id", how="left")

print("suppliers requiring further evaluation based on ratings, returns, and product performance",df)

plt.figure(figsize=(10, 5))
df.plot(x="supplier_name",y=["supplier_rating","profit","total_return"],kind="bar")
plt.title("supplier Performance Analysis")
plt.xlabel("suppliert")
plt.ylabel("Amount")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Q99 Find the top 5 products based on total sales revenue.

QUERY_99="SELECT products.product_name,SUM(sales.quantity*sales.selling_price) AS revenue FROM sales INNER JOIN products ON sales.product_id=products.product_id GROUP BY products.product_name ORDER BY revenue DESC LIMIT 5; "
df=pd.read_sql(QUERY_99,engine)
print(df)

# Q100. Create an overall business performance analysis combining sales, profit, inventory, returns, and expenses.

QUERY_SALE="SELECT SUM(quantity * selling_price) AS total_sales,SUM(quantity) AS total_units_sold FROM sales;"
df_sales=pd.read_sql(QUERY_SALE,engine)

query_profit="SELECT SUM(sales.quantity*sales.selling_price)-SUM(sales.quantity*products.cost_price) AS profit FROM sales INNER JOIN  products ON sales.product_id=products.product_id;"
df_profit=pd.read_sql(query_profit,engine)

query_inventory = "SELECT SUM(stock_received) AS total_stock_received, SUM(stock_sold) AS total_stock_sold, SUM(stock_damaged) AS total_stock_damaged FROM inventory;"
df_inventory = pd.read_sql(query_inventory, engine)

query_expenses = "SELECT SUM(expense_amount) AS total_expenses FROM expenses;"
df_expenses = pd.read_sql(query_expenses, engine)

query_returns = "SELECT SUM(return_quantity) AS total_returned_quantity FROM returns;"
df_returns = pd.read_sql(query_returns, engine)

business_performance = pd.concat([df_sales,df_profit,df_inventory,df_expenses,df_returns,],axis=1)
print("business performance analysis combining sales, profit, inventory, returns, and expenses",business_performance)

